services:
  backend:
    build: 
      context: ./docker/backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - ./docker/backend/src:/app/src
    networks:
      - archnet
    restart: unless-stopped

  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./docker/frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - archnet
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - archnet

  monitoring:
    build:
      context: ./docker/monitoring
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - archnet
    restart: unless-stopped

networks:
  archnet:
    driver: bridge
